app = "cats-of-asia"
primary_region = "sin"

[build]
dockerfile = "Dockerfile.flyio"

[processes]
web = "web"
cron = "supercronic /home/nonroot/crontab"

[http_service]
    processes = ["web"]
    force_https = true
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 0

