name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ vars.GO_VERSION }}

      - uses: ko-build/setup-ko@v0.6
      - run: KO_DOCKER_REPO="ghcr.io/haikoschol/cats-of-asia/web" ko build --bare ./cmd/web
      - run: KO_DOCKER_REPO="ghcr.io/haikoschol/cats-of-asia/publish" ko build --bare ./cmd/publish
