name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: ko-build/setup-ko@v0.6
      - run: ko build --bare ./cmd/web
        env:
          KO_DOCKER_REPO: ghcr.io/haikoschol/cats-of-asia
