name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20.x'
      - uses: actions/checkout@v2

      - id: govulncheck
        uses: golang/govulncheck-action@v1

      - uses: ko-build/setup-ko@v0.6
      - run: ko build --bare ./cmd/coabot
        env:
          KO_DOCKER_REPO: ghcr.io/haikoschol/cats-of-asia

